channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - jupyter_contrib_nbextensions
  - ipyvolume
  - pip
  - voila
  - bqplot
  - pip:
    - git+https://github.com/glue-viz/glue-jupyter.git
